name: Setup Python

description: |
  Set up Python and Poetry using .python-version (caches dependencies too)

runs:
  using: composite
  steps:
    - name: Get python version
      id: python-version
      shell: bash
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT
        echo "poetry-version=$(cat .poetry-version)" >> $GITHUB_OUTPUT

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '${{ steps.python-version.outputs.version }}'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ steps.python-version.outputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: false

    - name: Set up cache
      uses: actions/cache@v4
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
