name: lint

on:
  push: {}
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Install Deps
        uses: ./.github/actions/setup-python-and-install-deps

      - name: Flake8
        id: flake8
        run: poetry run flake8
        continue-on-error: true

      - name: Black
        id: black
        run: poetry run black --check .
        continue-on-error: true

      - name: MyPy
        id: mypy
        run: poetry run mypy .
        continue-on-error: true

      - name: Pylint
        id: pylint
        run: poetry run pylint ./tiltenv
        continue-on-error: true

      - name: isort
        id: isort
        run: poetry run isort --check .
        continue-on-error: true

      - name: Fail on lint errors
        if: ${{
            steps.flake8.outcome == 'failure'
            || steps.black.outcome == 'failure'
            || steps.mypy.outcome == 'failure'
            || steps.pylint.outcome == 'failure'
            || steps.isort.outcome == 'failure'
          }}
        run: |
          echo "Lint errors found"
          echo "  flake8: ${{ steps.flake8.outcome }}"
          echo "  black: ${{ steps.black.outcome }}"
          echo "  mypy: ${{ steps.mypy.outcome }}"
          echo "  pylint: ${{ steps.pylint.outcome }}"
          echo "  isort: ${{ steps.isort.outcome }}"
          exit 1
